Don't log something about "occ upgrade" if owncloud is not setup yet (FS#3484).

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -21,23 +21,25 @@ case "$1" in
         if [ -e "/etc/init.d/php5-fpm" ]; then
             invoke php5-fpm restart || true
         fi
-        if [ -x "/usr/bin/occ" ] && [ -s "/etc/owncloud/config.php" ] ; then
-            set +e
-            /usr/bin/occ upgrade
-            rc=$?
-            set -e
-            if [ "$rc" != "0" ] && [ "$rc" != "3" ]; then
-                echo "****************************************************************"
-                echo "** Automatic update failed, please run 'occ upgrade' manually **"
-                echo "** after the installation to finish upgrading the spreedme    **"
-                echo "** ownCloud application!                                      **"
-                echo "****************************************************************"
+        if [ -s "/etc/owncloud/config.php" ]; then
+            if [ -x "/usr/bin/occ" ]; then
+                set +e
+                /usr/bin/occ upgrade
+                rc=$?
+                set -e
+                if [ "$rc" != "0" ] && [ "$rc" != "3" ]; then
+                    echo "****************************************************************"
+                    echo "** Automatic update failed, please run 'occ upgrade' manually **"
+                    echo "** after the installation to finish upgrading the spreedme    **"
+                    echo "** ownCloud application!                                      **"
+                    echo "****************************************************************"
+                fi
+            else
+                echo "***************************************************************"
+                echo "** Please run 'occ upgrade' after the installation to finish **"
+                echo "** upgrading the spreedme ownCloud application!              **"
+                echo "***************************************************************"
             fi
-        else
-            echo "***************************************************************"
-            echo "** Please run 'occ upgrade' after the installation to finish **"
-            echo "** upgrading the spreedme ownCloud application!              **"
-            echo "***************************************************************"
         fi
         ;;
 
